# Generated by Django 5.1.3 on 2024-11-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joblisting',
            options={'ordering': ['-featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='joblisting',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
